name: Secrets test

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
  workflow_dispatch:

jobs:
  secrets-test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: echo secret ${{secrets.DB_PASSWORD}}
      - run: npm install
